/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nypproje;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author emre
 */

public class ChildPanel extends javax.swing.JFrame {

    /**
     * Creates new form ChildPanel
     */
    private List<int[]> exerciseList;
    private String kullaniciAdi;
    private List<String[]> reportList;
    private List<String[]> siralamaList;
    
    public ChildPanel(String kullaniciAdi) {
        exerciseList = new ArrayList<>();
        reportList = new ArrayList<>();
        this.kullaniciAdi=kullaniciAdi;
        initComponents();
        exerciseList = new ArrayList<>();
        loadExercisesFromSer();
        loadReportsFromSer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        baslaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alistirmaTablosu = new javax.swing.JTable();
        mesaj = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        siralamaButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        siralamaTablosu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("EGZERSİZLER");

        baslaButton.setText("BAŞLA");
        baslaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baslaButtonActionPerformed(evt);
            }
        });

        alistirmaTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alıştırma Kodu", "a", "b", "Soru Sayisi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        alistirmaTablosu.setToolTipText("");
        alistirmaTablosu.setShowGrid(true);
        jScrollPane1.setViewportView(alistirmaTablosu);
        if (alistirmaTablosu.getColumnModel().getColumnCount() > 0) {
            alistirmaTablosu.getColumnModel().getColumn(0).setResizable(false);
            alistirmaTablosu.getColumnModel().getColumn(1).setResizable(false);
            alistirmaTablosu.getColumnModel().getColumn(2).setResizable(false);
            alistirmaTablosu.getColumnModel().getColumn(3).setResizable(false);
        }

        closeButton.setText("ÇIKIŞ");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        siralamaButton.setText("Sıralama Göster");
        siralamaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siralamaButtonActionPerformed(evt);
            }
        });

        siralamaTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Çocuk Adı", "Puan", "Süre"
            }
        ));
        siralamaTablosu.setShowGrid(true);
        jScrollPane2.setViewportView(siralamaTablosu);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("SIRALAMA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(306, 306, 306))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(baslaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(siralamaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(baslaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mesaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siralamaButton)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baslaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baslaButtonActionPerformed
        // TODO add your handling code here:
        mesaj.setText("");
        DefaultTableModel model = (DefaultTableModel)alistirmaTablosu.getModel();
        int seciliRow = alistirmaTablosu.getSelectedRow();
        if(seciliRow == -1){
            if(alistirmaTablosu.getRowCount()==0){
                mesaj.setText("Lütfen alistirma ekleyiniz.");
            }else{
                mesaj.setText("Lütfen alistirma seciniz.");
            }
        }else{
            ExamPanel examPanel = new ExamPanel(exerciseList.get(seciliRow)[0],exerciseList.get(seciliRow)[1],exerciseList.get(seciliRow)[2], kullaniciAdi, seciliRow);
            examPanel.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_baslaButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        LoginPanel loginPanel = new LoginPanel();
        loginPanel.setVisible(true);
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void siralamaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siralamaButtonActionPerformed
        // TODO add your handling code here:
        loadReportsFromSer();
        siralamaList = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel)siralamaTablosu.getModel();
        model.setRowCount(0);
        int alistirmaKodu = alistirmaTablosu.getSelectedRow();
        for(String[] report: reportList){
            if(Double.parseDouble(report[2])==alistirmaKodu){
                int last = report.length - 1;
                Object[] eklenecek = {report[1],report[last-1],report[last]};
                model.addRow(eklenecek);
            }
        }

        // Satırları ekleme işleminden sonra sıralama yapmak için TableRowSorter kullanıyoruz
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        siralamaTablosu.setRowSorter(sorter);

        // Sıralama yapılacak sütunun indeksini belirleme (örneğin "Puan" sütunu)
        int columnIndex = 1; // "Puan" sütununun indeksi (0'dan başlayarak sayılır)

        // Sıralama işlemini yapılandırın
        sorter.setSortKeys(List.of(new RowSorter.SortKey(columnIndex, SortOrder.DESCENDING))); // Azalan şekilde sıralama

        // Tabloya satırları ekledikten sonra sıralama otomatik olarak yapılacak
    }//GEN-LAST:event_siralamaButtonActionPerformed

    private void updateTable(){
        DefaultTableModel model = (DefaultTableModel)alistirmaTablosu.getModel();
        model.setRowCount(0);
        int index = 1;
        for (int[] exercise : exerciseList) {
            Object[] eklenecek = {index,exercise[0],exercise[1],exercise[2]};
            model.addRow(eklenecek);
            index++;
        }
    }
    
    private void loadExercisesFromSer() {
        try {
            File file = new File("exercises.ser");
        
            // Ser dosyası mevcut değilse boş bir dosya oluştur
            if (!file.exists()) {
                file.createNewFile();
                exerciseList = new ArrayList<>();
                updateTable();
                return;
            }
 
            // Serileştirilmiş alıştırmaları okumak için FileInputStream ve ObjectInputStream kullanılır
            FileInputStream fileIn = new FileInputStream("exercises.ser");
            ObjectInputStream objectIn = new ObjectInputStream(fileIn);

            // Serileştirilmiş alıştırmaları oku
            exerciseList = (List<int[]>) objectIn.readObject();

            // Kaynakları serbest bırak
            objectIn.close();
            fileIn.close();

            // Alıştırmaları güncelle
            updateTable();
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
    
    private void loadReportsFromSer(){
        try {
            FileInputStream fileIn = new FileInputStream("reports.ser");
            ObjectInputStream objectIn = new ObjectInputStream(fileIn);

            // reports.ser dosyasından verileri oku ve reportList'e at
            reportList = (List<String[]>) objectIn.readObject();

            objectIn.close();
            fileIn.close();
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
            // Hata durumunda gerekli işlemleri yapabilirsiniz
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChildPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChildPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChildPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChildPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChildPanel("emre").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alistirmaTablosu;
    private javax.swing.JButton baslaButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mesaj;
    private javax.swing.JButton siralamaButton;
    private javax.swing.JTable siralamaTablosu;
    // End of variables declaration//GEN-END:variables
}
